# Generated by Django 3.2.5 on 2021-12-02 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listings_byuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='CurrentUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyed_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
