# Generated by Django 3.2.5 on 2021-12-03 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_currentuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='CurrentUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyed_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
