# Generated by Django 3.2.5 on 2021-12-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listings_currentuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
