# Generated by Django 3.2.5 on 2021-12-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listings_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='com_listing',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='com_user',
            new_name='user',
        ),
    ]
